z0:
    z:
        0.8
    ELG_params:
        p_max: 0.53
        Q: 10.
        logM_cut: 12.3
        kappa: 1.
        sigma: 0.58
        logM1: 13.53
        alpha: 0.9
        gamma: 4.12
        A_s: 1.
        alpha_c: 0
        alpha_s: 1
        s: 0
        s_v: 0
        s_p: 0
        s_r: 0
        Acent: 0
        Asat: 0
        Bcent: 0
        Bsat: 0